name: snow-howitzer
version: 0.0.1
license: BSD3
license-file: LICENSE
author: Daniil Iaitskov
maintainer: dyaitskov@gmail.com
category: Database
build-type: Simple
description: Tool encforces an avalanche of Haskell package updates once new GHC is released

ghc-options: -O2 -Wall


language: GHC2021

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - LambdaCase
  - ImportQualifiedPost
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedStrings
  - RecordWildCards
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - UnicodeSyntax
  - GADTs
  - PolyKinds
  - RankNTypes
  - TypeOperators
  - TypeApplications

dependencies:
  - SHA
  - aeson
  - ansi-terminal
  - async
  - base
  - base64-bytestring
  - binary
  - bytestring
  - containers
  - deepseq
  - directory
  - entropy
  - exceptions
  - filepath
  - fmt
  - generic-lens
  - github
  - hashable
  - http-client
  - http-client-tls
  - http-conduit
  - http-types
  - katip
  - lens
  - lens-aeson
  - microlens
  - mtl
  - network-uri
  - open-browser
  - optparse-applicative
  - postgresql-simple
  - pretty
  - process
  - raw-strings-qq
  - regex-tdfa
  - regression-simple
  - relude
  - req
  - safe
  - safe-exceptions
  - scientific
  - servant
  - servant-server
  - sqlite-simple
  - stm
  - text
  - template-haskell
  - time
  - tls
  - tuple
  - unix
  - unliftio
  - unliftio-pool
  - unordered-containers
  - uuid
  - wai
  - wai-app-static
  - wai-logger
  - warp

library:
  source-dirs: src
  generated-exposed-modules:
    - Paths_snow_howitzer

executables:
  snow-howitzer: &exe
    main: Main.hs
    source-dirs: exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - snow-howitzer

tests:
  snow-howiztertest:
    <<: *exe
    ghc-options: -dynamic -rtsopts -threaded # no -with-rtsopts=-N
    main: Driver
    source-dirs:
      - test
    dependencies:
      - snow-howitzer
      - envy
      - generic-random
      - HUnit
      - network
      - quickcheck-instances
      - tasty
      - tasty-discover
      - tasty-expected-failure
      - tasty-golden
      - tasty-hunit
      - tasty-quickcheck
